### ISSUE TITLE
First draft of a parser using the recipe example

### ISSUE THREAD

**Issue by ocefpaf** [pangeo-forge/pangeo-smithy#1]
@rabernat draft example is quite complete and we started writing a parser for it as an exercise during the OHW19.

@rabernat what is your student GitHub handle? I'd like to continue working on that with her here.

**Comment by rabernat** [comment]
Shanice is @stb2145. Thanks for working on this project!

**Comment by ocefpaf** [comment]
> Shanice is @stb2145. Thanks for working on this project!

Thanks!

@stb2145 can you send a PR with the draft we started? I believe we'll evolve faster interacting here then in person :smile:.

**Comment by shanicetbailey** [comment]
Hi, trying to push to the repo but I am getting `remote: Permission to pangeo-forge/pangeo-smithy.git denied to stb2145.`
`fatal: unable to access 'https://github.com/pangeo-forge/pangeo-smithy.git/': The requested URL returned error: 403`

**Comment by ocefpaf** [comment]
@stb2145 I answered you on slack but let's keep the communication here to avoid confusion. As I mentioned there you do not have direct access to ttps://github.com/pangeo-forge/pangeo-smithy ([403 is forbidden error](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403)). Even though we can grant you access you should take a look at the fork-branch-PR model. See https://help.github.com/en/articles/creating-a-pull-request-from-a-fork

You also mentioned on slack:

> So I should push to my fork and then do the pull request on Github?

Yep. Once you push to your fork you can create the PR. Depending on your git version you'll get a link to create the PR in your terminal as soon as you push. If not, you can navigate to https://github.com/pangeo-forge/pangeo-smithy and follow the instructions [starting from step 2](https://help.github.com/en/articles/creating-a-pull-request-from-a-fork).

**Comment by shanicetbailey** [comment]
Alright, I made a pull request for the "meta.yaml" and "parser1.ipynb" files. Thanks @ocefpaf
